void main() {
  List<int> varLst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  // Extract even numbers from a list of integers. Code generated by
  // GitHub Copilot chat.
  List<int> resLst = varLst.where((i) => i.isEven).toList();

  print(resLst);
}
