name: dart_explore
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
version: 1.2.3
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs

environment:
  sdk: '>=2.17.1 <4.0.0'
  
dependencies:
  intl: ^0.17.0
  test: ^1.21.1
dev_dependencies:
